# Define your RISC-V toolchain path here
# Linux example:
# RISCV_GCC_PREFIX = "/opt/riscv/bin/riscv32-unknown-elf"
# 
# Windows example:
RISCV_GCC_PREFIX = r"C:\xpack-riscv-none-elf-gcc-13.2.0-2\bin\riscv-none-elf"
# 
# We will update this file according to our test environment, 
# unlike other files under the folder user_files. So you are
# free to set a toolchain path that only works in your system
# here :)